steps:
  count: 30
  delay: 100

hotel:
  floors:
    number: 4
  elevator:
    capacity: 3
    number: 2
  spawn-probability:
    ground: 0.65
    other: 0.65
  display:
    column-width:
      floor: 5
      elevator: 24
      persons: 20
